Makefile
Added genesis tooling command to makefile that allows us to purge the wasm from genesis exports to help with https://github.com/classic-terra/classic/issues/12
----
=> Added command in makefile to purge wasm from genesis json

.github/workflows/docker.yml
I found out back in June that there was some issue when upgrading to the golang:1.19-alpine image when resolving the libwasm dependency on ARM64 architectures. That is why Woelig & I implemented the alternate Ubuntu based version, as it did not seem to suffer from the same issue and also made it easier for us to implement the "validator-auto-registration" logic to support the terra-operator. If this PR fixes the issue I would suggest that we consider targeting the Ubuntu image (Dockerfile.terraclassic.terrad-binary) as our default for the docker.yml workflow to support as many CPU architectures as possible. Alternately we can build both by extending the workflow with some more steps :)
Disabled linux/arm64 target in docker.yml workflow
=> Disable ARM64 target to allow alpine build to pass

.gitignore, app/app.go, app/legacy/migrate.go, app/upgrades/v2/constants.go, app/upgrades/v2/upgrades.go, custom/auth/ante/ante.go, go.mod, go.sum, scripts/README.md, scripts/run-node.sh, scripts/upgrade-test.sh, x/wasm/keeper/test_utils.go, x/wasm/types/expected_keeper.go
also fix version map issue.
the problem is that in current mainnet version of v1.0.4, we forget to register module version map to UpgradeKeeper
`app.UpgradeKeeper.SetModuleVersionMap(ctx, app.mm.GetVersionMap())`
since 1.0.4 upgrade keeper doesn't have version map registered, it will lead to future upgrade handler fails due to empty version map. Hot fix for v1.0.4 here:
https://github.com/classic-terra/classic/tree/v1.0.4-upgrade-version-map-hotfix
Working upgrade here from v1.0.4-upgrade-version-map-hotfix to main:
----
=> Bump ibc go 34

custom/auth/client/utils/feeutils.go
The previous fix of adding the ante.TaxPowerUpgradeHeight did not pass integration testing.  The problem is that the clientCtx.Height is not equivalent to the chain height, and thus is never greater than the TaxPowerUpgradeHeight.
By simply removing this conditional, it will correctly tax uluna.  It is in the LCD client so it does not need to be wrapped in block height guards 
----
=> allow uluna to be taxed

Makefile
This PR fixes image build errors on Apple Silicon machines, and removes warnings from Docker when using the image.
----
=> Fix makefile for linux builds

x/treasury/keeper/keeper.go, x/treasury/keeper/params.go
- Change logic`SetBurnSplitRate`. It should be set directly in paramspace. 
----
=> Fix Panic when upgrade to v2

.gitignore, app/app.go, types/alias.go, types/fork/height.go
Move version map to BeginBlocker
----
=> move version map register to begin block

x/market/keeper/swap.go, x/market/keeper/swap_test.go, x/market/types/errors.go
This is some old code I wrote back in my first PR for TFL. The idea is to add a 2T hardcap, which should probably be set to 10B based on 3568,  that will ensure we can never get into a situation of minting  infinite supply  when we eventually re-enable swapping from USTC => LUNC.
----
=> Constrained pool to ensure LUNC can never have more then 2T supply

custom/auth/client/utils/feeutils.go
=> fix ungraceful error on failed client tax query

CHANGELOG.md, app/app.go
This is a complementary feature for operators who are trying to use version > v1.0 for importing the genesis of Columbus mainnet.
For example, genesis importing is essential if someone wants to use PebbleDB implementation, in which case a new DB must be built based on v1.0.x
----
=> feat: panic at columbus genesis

Makefile, docker-compose.yml
Parametrized the local testnet tooling. A local testnet with 2 validators and with chain id "testnet-1" can be spun up using the following commands:
`TESTNET_NVAL=2 TESTNET_CHAINID=testnet-1 make localnet-start`
Default values are `4` and `chain-<rand(6)>`
I also increased the maximum number of possible validators in the localnet to 6, because the min. number of validators on columbus-5 would be 5 (due to 20% voting power cap).
=> refactor: add number of validators and chain id as testnet parameters

tests/README.md
Closes: #69 
I add this pr so that we can comment directly to where changes are needed
cc: @ZaradarBH @inon-man @fragwuerdig @edk208 
----
=> docs: add testing framework document

wasmbinding/bindings/msg.go, wasmbinding/bindings/query.go, wasmbinding/helper.go, wasmbinding/message_plugin.go, wasmbinding/queries.go, wasmbinding/query_plugin.go, wasmbinding/wasm.go
This adds wasmbindings/bindings folder. I will add more in the wasmbindings folder as I go. Introduces `TerraMsg` and `TerraQuery` types. These are the JSON bindings for the custom Messages and Queries from market/treasury/oracle module.
=> add wasm-bindings for canonical wasmd

.github/workflows/sims.yml, .github/workflows/test.yml
For some reason this workflow still contained go 1.17. I stumbled across this in the canonical-wasm branch, where it actually breaks the workflow. I propose to update that to 1.18.
BTW: the liveness test contains go version 1.17 too... So probably a solution for #171 ?
=> Update `sims.yml` to contain go 1.18

custom/auth/ante/ante_test.go, custom/auth/ante/tax_test.go, wasmbinding/bindings/msg.go, wasmbinding/bindings/query.go
This PR aims to fix the broken unit-tests on canonical-wasm branch. The fixes mostly relate to the fact that `NewMsgInstantiateContract` and `NewMsgExecuteContract` are not available in canonical wasmd.
=> fix some broken unit tests after switch to canonical wasmd

Makefile, contrib/localnet/deposit-test.sh
This is just the test I used locally to test the min-initial-deposit feature. Run inside root folder of repo - like so:
`contrib/localnet/deposit-test.sh`
I leave it here more or less for reference. As the good ol' devs say: Works on my machine!
=> add script for min initial deposit ratio test

.github/workflows/test.yml, cmd/terrad/testnet.go
This addresses #171. Changes include:
- Let the nodes ALWAYS run. But only some of them are active validators.
- Provide TESTNET_NVAL=6 in liveness test to make sure we always restart validator nodes
=> fix issues with liveness test

Makefile, app/app.go, app/keepers/keys.go, app/modules.go, app/sim_test.go, cmd/terrad/config.go, cmd/terrad/root.go, custom/auth/ante/ante.go, custom/auth/ante/ante_test.go, custom/auth/ante/integration_test.go, custom/auth/ante/tax_test.go, temp.txt, wasmbinding/helper.go, wasmbinding/message_plugin.go, wasmbinding/queries.go, wasmbinding/query_plugin.go, x/feeshare/ante/ante.go, x/feeshare/ante/ante_test.go, x/feeshare/integration_test.go, x/feeshare/keeper/keeper.go, x/feeshare/types/feeshare.pb.go, x/feeshare/types/genesis.pb.go, x/feeshare/types/query.pb.go, x/feeshare/types/query.pb.gw.go, x/feeshare/types/tx.pb.go, x/feeshare/types/tx.pb.gw.go
Add the default wasm config to the `app.toml` config template for `terrad init` command. Otherwise we may have ulimited contract query gas when someone creates a validator node from scratch.
**IMPORTANT**: We will also have to include this in upgrade instructions for the validators.
=> add default wasm config to init cmd

custom/auth/client/utils/feeutils.go, x/feeshare/types/feeshare.pb.go, x/feeshare/types/genesis.pb.go, x/feeshare/types/query.pb.go, x/feeshare/types/query.pb.gw.go, x/feeshare/types/tx.pb.go, x/feeshare/types/tx.pb.gw.go
The stability and/or burn tax are always subtracted from the fee amount of the transaction. When issuing a transaction with `terrad` by providing `--gas auto` then it does not take the gas adjustment into account when calculating the fees from the required gas. This PR fixes odd behavior when gas price settings on the local client are slightly lower than on the chain.
=> fix gas adjustment not being taken into account when calculating fees in `feeutils.go`

custom/wasm/client/cli/tx.go, custom/wasm/client/rest/tx.go, custom/wasm/module.go
- fix missing label option in `custom/wasm/client/cli/tx.go`
- fix unhandled label in `custom/wasm/client/rest/tx.go
=> fix missing label in custom/wasm/client

custom/wasm/keeper/handler_plugin.go
PR #268 made an unintended state machine breaking change to correct the linting error.
=> fix: wasm DispatchMsg should return events and data

custom/auth/ante/tax.go, custom/auth/ante/tax_test.go, types/alias.go
Dear L1 Task Force,
I hereby humbly ask you to accept these code changes. This pull request will exempt ibc denoms from on chain (burn) taxes. This is a feature that passed governance approval back in January and slipped because the original implementation from me was merged into old frozen main. The approved on-chain proposal can be found [here](https://station.terraclassic.community/proposal/columbus-5/11267)
Changes include:
- Implemention of the the exemption logic in the ante handler
- Implementation of a Test that would fail if the exemption was not present
Thank you for considering this PR. Your ongoing work and engagement for this Blockchain is very much appreciated.
Best,
Till
=> feat: exempt ibc denoms from tax

cmd/terrad/root.go, go.mod, go.sum
Apply the new classic-terra/cosmos-sdk v0.46.14-terra.2 to set iavl-disable-fastnode to true by default. The iavl-disable-fastnode and iavl-disable-fastnode settings can also be controlled using app.toml.
In the past, the value of iavlDisableFastNodeDefault in Terra Classic was set to true, so the IAVL FastNode feature has never been used in Terra Classic. If this value is changed to false, migration will be forced to occur at every node startup.
When testing the migration of Columbus-5, it took approximately 50 minutes on a machine with a 3.6Ghz Intel Core i9 and 128GB of memory.
In addition, the recently discovered bug in IAVL (https://github.com/cosmos/iavl/pull/805) only occurs in nodes using IAVL fast node.
=> fix: set default `iavl-disable-fastnode` to true

app/app.go, app/upgrades/forks/constants.go, app/upgrades/forks/forks.go, scripts/upgrade-test.sh, types/alias.go, types/fork/fork.go
Dear L1 Team. During the mainnet upgrade the min. validator commission was accidentally set to 0%. This immediately led to creation of 0% validators and also validators lowering their commissions. Simple governance proposal to set the commission to 5% is _not_ sufficient. This is why I prepared this fix to be applied as fork guard or hotfix upgrade (meaning: it's a state machine breaking upgrade, but due to a fork guard validators can install without chain halt).
I suggest to test it on rebel-2 first.
**TODO**: Coordinate/Communication on proper fork block heights.
=> fix: set min commission back to 5%

cmd/terrad/root.go, go.mod, go.sum, x/market/keeper/params.go, x/oracle/keeper/params.go, x/oracle/keeper/querier.go, x/treasury/keeper/params.go
[fix: update IAVL version](https://github.com/classic-terra/cosmos-sdk/pull/13) has concurrency panic fix with default iavl-disable-fastnode option to `true`
[fix(store): use stdout logger instead of nop](https://github.com/classic-terra/cosmos-sdk/pull/14) will print log when upgrading IAVL store to fastnode
`terrad prune` Prune app history states by keeping the recent heights and deleting old heights.
`terrad snapshots` Manage local snapshots for State Sync feature.
Use a modified version of tm-db that allows for a maximum of 32768 open files and several performance patches. Because it uses multiple goleveldb instances, [check your system limits](https://linuxhint.com/increase-open-file-limit-ubuntu/) to have enough (e.g. 262144) open file limits. 
Replace …
=> feat: updates for v2.2.2

x/dyncomm/abci.go
This PR is just setting the epoch length of dyncomm modules recalculation from 10minutes to 7days (how it's supposed to be on `columbus-5` mainnet). This change needs a chain halt on rebel-2 network and will be coordinated with the testnet validators accordingly. This PR is supposed to mark `v2.3.0` release to introduce dyncomm on `columbus-5`.
=> fix: last cleanup - prepare v2.3.0

.golangci.yml, app/testing/test_suite.go, custom/staking/module_test.go, wasmbinding/test/helpers_test.go, x/dyncomm/ante/ante.go, x/dyncomm/ante/ante_test.go, x/dyncomm/module.go, x/dyncomm/types/codec.go, x/dyncomm/types/query.pb.go, x/dyncomm/types/query.pb.gw.go
Check tx skipped in dyncomm decorator will broadcast failed txs to other nodes, thus posing a potential risk. This pr seeks to stricten the rule in ante decorator. 
Full e2e test case is refactored in place of old EditValidatorAccountSequence with blocks simulation to ensure checktx and delivertx accSeq invariant when failed.
----
=> stricter constraint that fails unqualified commission at check tx

app/app.go, app/upgrades/v6_1/constants.go, app/upgrades/v6_1/upgrades.go, contrib/updates/prepare_cosmovisor.sh
=> add upgrade handler for v6_1

app/keepers/keepers.go, app/modules.go, app/params/params.go, custom/bank/client/cli/tx.go, scripts/burn-tax-exemption-test.sh, types/assets/assets.go, x/treasury/client/cli/gov_tx.go
This PR fix all issues related to IBC Hooks and PFM setups. Additionally, it adds a cli for multi-send functionality in bank.
=> Fix IBC Hooks and PFM

custom/auth/ante/fee_tax.go
This bug slipped through when the `MsgExec` was added to the tax handling.
=> fix: wrong logic in handling tax for `MsgExec`

app/keepers/keepers.go, app/keepers/routers.go, app/modules.go, app/upgrades/v7/constants.go, go.mod, go.sum, tests/e2e/e2e_test.go
PFM has been a recurring source for high severity security issues over the last couple of months. See the recent upgrade on Neutron, which has given light to yet another problem. The feature is not necessary to on-board Enterprise DAO. So it might be a good idea to just leave it out of the game at all for now. Changes include:
- Remove PFM from upcoming chain upgrade
=> security: revert pfm feature

app/app.go, custom/auth/ante/ante.go, x/dyncomm/ante/ante.go, x/dyncomm/ante/ante_test.go
Referencing closed PR #449 
---
Let's be really pedantic.
ICA host capabilities are currently disabled on Terra Classic (ICA host parameter enabled is set to false). But if a param change governance prop passes that opens Terra Classic as ICA host chain, then the MsgEditValidator could be triggered via ICA - meaning MsgEditValidator comes wrapped inside a MsgRecvPackage.
Unit tests included.
Phew.
=> fix: take ICA into account for dyncomm ante

app/app.go, custom/auth/ante/ante.go, x/dyncomm/ante/ante.go, x/dyncomm/ante/ante_test.go
Fix handling MsgExec (authz) for dyncomm handler and add unit test
=> Fix dyncomm ante handler

app/app.go, app/upgrades/v7_1/constants.go, app/upgrades/v7_1/upgrades.go, contrib/updates/prepare_cosmovisor.sh
Introduce upgrade name `v7_1` for next chain halt proposal
=> deps: add uprade name `v7_1`

app/upgrades/v8_1/upgrades.go, custom/auth/ante/ante.go, custom/auth/ante/expected_keeper.go, custom/auth/ante/fee.go, custom/auth/ante/fee_burntax.go, custom/auth/ante/fee_test.go, x/treasury/types/params.go
adjusted split logic to reflect the intention
changed tests to use coin instead of deccoin as the true calculations also use coins and there are rounding differences between tests and real logic with small numbers that make the tests fail
=> Adjust oracle split logic

Makefile, README.md, app/keepers/keepers.go, app/upgrades/v8/upgrades.go, contrib/updates/Dockerfile.cosmovisor, go.mod, go.sum
This PR does:
- Update wasmvm version to v1.5.4 which has fixes for CWA-2024-003 and CWA-2024-004.
- Use wasmd version v0.46.0 to fixes CWA-2024-005
References:
https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-003.md
https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-004.md
https://github.com/CosmWasm/advisories/blob/main/CWAs/CWA-2024-005.md
=> feat: wasmd v0.46.0

app/keepers/keepers.go
This is a last second change request for v3.4.1
This enabled cosmwasm interface versions `1_2` and `1_3`
=> feat: wasmvm interface versions 1_2, 1_3
