- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/proto.yml
- Dockerfile.terraclassic.terrad-binary
- Makefile
- contrib/images/Makefile
- docker-compose.yml
- docker-compose/docker-compose.yml
- docker/README.md
- docker/build_all.sh
> Fix Github Action not running

- custom/auth/ante/ante.go
- custom/auth/ante/ante_test.go
- custom/auth/ante/burntax.go
- custom/auth/ante/burntax_test.go
> - "Burntax split" in antehandler for Eds prop

- custom/auth/ante/burntax.go
Clean-up the broken windows left behind by the burntax antehandler code :)
> gofumpt'ing burntax

- scripts/README.md
- scripts/run-node.sh
Add a script for quickly spinning up a local node for testing
----
> add quick script for running test node

- custom/auth/ante/burntax_test.go
add the four following cases:
1. MsgSend(binance -> binance): should pass
2. MsgSend(normal -> normal): should tax
3. MsgSend(binance -> normal), MsgSend(binance -> binance): should tax
4. MsgSend(binance -> binance), MsgMultiSend(binance -> normal, binance -> binance): should tax
tests are passing
----
> add whitelist test

- x/market/keeper/swap.go
- x/market/keeper/swap_test.go
- x/market/types/errors.go
> Revert "Constrained pool to ensure LUNC can never have more then 2T supply"

- .github/workflows/test.yml
- Dockerfile
- Makefile
- README.md
- contrib/images/Makefile
- contrib/images/terrad-env/Dockerfile
- contrib/images/terrad-env/cosmovisor-wrapper.sh
- contrib/updates/Dockerfile.cosmovisor
- contrib/updates/Makefile
- contrib/updates/docker-compose.yml
- contrib/updates/prepare_cosmovisor.sh
- contrib/updates/upgrade-test.sh
Closes: #87 
Add upgrade-test to github actions
1. Setup a localnet of 4 nodes
2. Add cosmovisor to these 4 nodes
3. Start localnet
4. Upgrade through cosmovisor
5. Check if all 4 nodes are up after upgrade
----
> Main branch: gh update test

- CHANGELOG.md
Adding missing changelogs
----
> chore: add missing changelogs

- .github/ISSUE_TEMPLATE/feature_request.md
Adding  "acceptance criteria" section to feature_request.md
> add acceptance criteria section to feature_request.md

- .github/workflows/codeql.yml
- app/encoding.go
Add codeql ci from crypto-com
----
> ci: add codeql ci

- app/app.go
Added app.DistrKeeper reference to HandlerOptions when instantiating the AnteHandler
> Add app.DistrKeeper to HandlerOptions during AnteHandler instantiation

- app/app.go
- app/keepers/keys.go
- app/upgrades/v4/constants.go
- go.mod
- go.sum
- scripts/upgrade-test.sh
fix upgrade handler and setup store loaders
----
> fix upgrade handler

- .github/workflows/release.yml
- Dockerfile
- Makefile
Add release action for `terrad` binary checksums, closes: #216 
----
> Add release action

- CHANGELOG.md
Updated Unreleased section to v2.1.2 in CHANGELOG.md
> chore: prepare v2.1.2 release

- custom/auth/ante/fee_tax.go
Contribution by @fragwuerdig from PR #333
> fix: remove panic from ante/tax

- proto/terra/dyncomm/v1beta1/query.proto
- x/dyncomm/client/cli/query.go
- x/dyncomm/keeper/querier.go
- x/dyncomm/module.go
- x/dyncomm/types/query.pb.go
- x/dyncomm/types/query.pb.gw.go
add cli for dyncomm, related to #355
> add cli for dyncomm

- x/dyncomm/keeper/dyncomm.go
Wrong value stored in DynCommissionRate
> Fix regression

- README.md
Can we please remove that? Thank you...
> docs: remove TR remainders

- app/keepers/keepers.go
Add params key table on appKeepers to prevent app hash
> v3.0.3: fix params keys table

- x/tax/types/compute_test.go
Reverts classic-terra/core#589
> Revert "test: add regression test for IBC tax fix"

- app/upgrades/v13/helper.go
- app/upgrades/v13/upgrades.go
> chore: update log info to debug
